# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 480ee239bfd1f30a6cf8e5b27af29bff0ce8f00d4f5df9cddb9af142c15d481cfbaca55a773552e4cae239e8c718692c30d7e336b86c4794d96825a1608106d5

test:
  secret_key_base: 10436be32cf723393c97dc23126e670c8e8dcd08af50e26e563bf911b058b93ba749d2aeb2b482ac2d2285d9074602bfff5671b8bcf19152c566f8c368be2c00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
